version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      JWT_KEY: "your_jwt_secret_here"
    depends_on:
      - db
      - migration
    volumes:
      - ./config.yaml:/app/config.yaml

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=postgres migrate
    volumes:
      - ./internal/db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  pgdata: